#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=/D/ztex

# The name of the jar archive
JARTARGET=USB_Test.jar
# Java Classes that have to be build 
CLASSTARGETS=USB_Test.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=
# Extra java libraries
CLASSPATH=

# ihx files (firmware ROM files) that have to be build 
IHXTARGETS=usb-test.ihx
# Extra Dependencies for ihx files
IHXEXTRADEPS=

# Extra files that should be included into th jar archive
EXTRAJARFILES=usb-test.ihx ../usb_test.bit
EXTRAJARFLAGS=

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
